In [2]:
#1.Write a program to write 5-dimensional array with all zeroes and ones
import random
import numpy as np
array01_5d=np.random.randint(0,2,(1,2,3,4,5))
print("5-dimensional array with all zeros and ones:\n",array01_5d)

5-dimensional array with all zeros and ones:
 [[[[[0 0 1 1 1]
    [0 1 0 1 0]
    [0 0 1 1 1]
    [1 0 0 0 0]]

   [[0 0 1 1 0]
    [1 1 0 1 1]
    [0 0 0 0 0]
    [1 0 1 0 1]]

   [[0 1 0 0 0]
    [0 1 0 0 1]
    [0 1 0 1 0]
    [0 1 1 1 1]]]


  [[[1 1 0 0 0]
    [1 0 1 1 0]
    [1 1 0 0 0]
    [1 0 1 1 1]]

   [[0 0 1 0 1]
    [0 1 0 1 0]
    [0 0 0 0 0]
    [1 1 0 1 1]]

   [[0 0 0 1 0]
    [1 1 1 1 0]
    [0 1 1 0 0]
    [0 1 1 1 1]]]]]


In [24]:
#2.Write a program to create an array of 10 zeros,10 ones and 10 fives in rows 1,2 and 3 respectively 
# which create a new array of shape (3,10)
n_array=np.array([0,1,5])
t_array=np.repeat(a,10)
r_array=t_array.reshape(3,10)
print(r_array)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5 5]]


In [26]:
#3.Write a program to create a 3x4 matrix filled with values from 10 to 21
f_array=np.random.randint(10,22,(3,4))    #21 included
print("3x4 matrix filled with values from 10 to 21:\n",f_array)

3x4 matrix filled with values from 10 to 21:
 [[10 17 18 16]
 [21 11 14 16]
 [13 20 21 18]]


In [67]:
#4.Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to 01,2,3,4,5,6,7,8,9
dm_10x10=np.diag(range(0,10))
print("10x10 zero matrix with elements from 0 to 9 as main diagonal:\n",dm_10x10)

10x10 zero matrix with elements from 0 to 9 as main diagonal:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


In [112]:
#5.Write a program to create a 4x4 array. Create an array from given array
#by swapping the first and last columns, second and third columns.
g_array=np.arange(1,17).reshape(4,4)
print("Given 4x4 array:\n",g_array)
c1_arr=g_array[[0,1,2,3],[0,0,0,0]].reshape(4,1)
c2_arr=g_array[[0,1,2,3],[1,1,1,1]].reshape(4,1)
c3_arr=g_array[[0,1,2,3],[2,2,2,2]].reshape(4,1)
c4_arr=g_array[[0,1,2,3],[3,3,3,3]].reshape(4,1)
swapped_array=np.concatenate([c4_arr,c3_arr,c2_arr,c1_arr],axis=1)
print("Array formed by swapping the first and last columns, second and third columns:\n",swapped_array)

Given 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array formed by swapping the first and last columns, second and third columns:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [73]:
#6.Write a program to reverse an array(the first element becomes the last)
#given array : [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
giv_arr=np.arange(12,28)
print("Given array:",giv_arr)
rev_arr=given_arr[::-1]
print("Reversed array:",rev_arr)

Given array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
Reversed array: [27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [106]:
#7.Write a program to access all the elements greater than 30,less than 80 and multiples of 5
#from an array of shape (10,10) with elements ranging from 1 to 100
g_arr=np.random.randint(1,101,(10,10))
print("Given 10x10 array with elements ranging from 1 to 100:\n",g_arr)
condition_arr=g_arr[np.where((g_arr>30)&(g_arr<80)&(g_arr%5==0))]
print("Array with elements greater than 30,less than 80 and multiples of 5:\n",condition_arr)

Given 10x10 array with elements ranging from 1 to 100:
 [[28 28 80 25 82 30 69 97  6 86]
 [62 18  6 59  6 49 32 44 27 34]
 [27 15 33 61 59 32 36 39 12 19]
 [72 20 33 34 10 48 58 11 40 12]
 [ 7 95 85 25 21 87 97 10 83 58]
 [89 17 33 20 49 19  6 61  9  6]
 [75 86 39 81 30 75 32 69 83 52]
 [20 82 67 68 11 96 76 95 62 39]
 [89 50 85 96 71 57 91 51  6 96]
 [74 31 95 57 25 27 96 21 42 14]]
Array with elements greater than 30,less than 80 and multiples of 5:
 [40 75 75 50]


In [111]:
#8.Write a program to create a 2-D array with 1 on the border and 0 inside.
r=int(input("Enter number of rows: "))
c=int(input("Enter number of columns: "))
X=np.ones((r,c),dtype=int)
i=1                        #since 0's should not be in 0th row index 
j=1                        #and 0th column index
while i<int(r-1):          #avoiding last row and last column,so use < condition.Also,i<r-1 & j<c-1 because row_index
    while j<int(c-1):      #& column_index are always 1 no. less than mathematical row_no. & column_no.since ind_vals are from 0
        X[i,j]=0           #integer based indexing
        j=j+1              #column increasing, same row. when last column is being reached, break out of loop
    i=i+1                  #next row
    j=1                    #again starting from 1st column
    
print("\n2-D array of shape ({},{}) with 1 on the border and 0 inside:".format(r,c))
print(X)

Enter number of rows: 8
Enter number of columns: 6

2-D array of shape (8,6) with 1 on the border and 0 inside:
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [125]:
#9.Write a program to create a checkerboard pattern. Don't use default array function.
array_01=np.tile([0,1],(1,4))
array_10=np.tile([1,0],(1,4))
c_arr=np.concatenate([array_01,array_10],axis=0)  #row cancatenation
ch_pat=np.vstack([c_arr,c_arr,c_arr,c_arr])   #row cancetanation
print("Checkerboard pattern with 0's and 1's:")
print(ch_pat)

Checkerboard pattern with 0's and 1's:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [97]:
#10.Write a program to find common values between two arrays.
#Expected output: array1: [10 20 40 60], array2: [10, 30, 40,50]
a1=np.array([10,20,30,40,50,60,70,80,90,100])
a2=np.array([10,20,40,60])
a3=np.array([10,30,40,50])
print("array1:\n",np.intersect1d(a1,a2))
print("array2:\n",np.intersect1d(a1,a3))

array1:
 [10 20 40 60]
array2:
 [10 30 40 50]


In [126]:
#11.Write a program to create a 2d array and then reshape into 1d array
arr_2d=np.random.rand(5,5)
print("2-D array:\n",arr_2d)
arr_1d=arr_2d.flatten()
print("Reshaped into 1-D array:\n",arr_1d)
arr_1d.ndim

2-D array:
 [[0.61999565 0.3657672  0.52026845 0.573132   0.15501744]
 [0.1883986  0.65313918 0.93180487 0.11486508 0.84839833]
 [0.51333097 0.19110366 0.59194367 0.77466869 0.20666603]
 [0.12775724 0.02642054 0.09219975 0.53646423 0.89614949]
 [0.00360698 0.56961244 0.04842114 0.41304116 0.55419771]]
Reshaped into 1-D array:
 [0.61999565 0.3657672  0.52026845 0.573132   0.15501744 0.1883986
 0.65313918 0.93180487 0.11486508 0.84839833 0.51333097 0.19110366
 0.59194367 0.77466869 0.20666603 0.12775724 0.02642054 0.09219975
 0.53646423 0.89614949 0.00360698 0.56961244 0.04842114 0.41304116
 0.55419771]


1

In [127]:
#12.Write a user-defined function to create a 1-d or 2-d array from scratch without using array functions
def create_array():
    l1=[]
    l2=[]
    noe1=int(input("Enter number of elements you want in the 1st list: "))
    i=1
    while i<=int(noe1):
        element_l1=input("Enter an element for 1st list: ")
        l1.append(element_l1)
        i=i+1
    noe2=int(input("Enter number of elements you want in the 2nd list: "))
    j=1
    while j<=int(noe2):
        element_l2=input("Enter an element for 2nd list: ")
        l2.append(element_l2)
        j=j+1
    array_c=[l1,l2]
    print("2-d array generated from scratch, using nested lists:\n",array_c)
    print(type(array_c))
 #IN PROGRESS

In [139]:
create_array()

Enter number of elements you want in the 1st list: 2
Enter an element for 1st list: 3
Enter an element for 1st list: 4
Enter number of elements you want in the 2nd list: 2
Enter an element for 2nd list: 4
Enter an element for 2nd list: 5
2-d array generated from scratch, using nested lists:
 [['3', '4'], ['4', '5']]
<class 'list'>
