### Import the required libraries to perform following tasks 
1. what is the difference between list and array (min of 4 points )
2. Write python code to create 3d array in different ways with 15 elements.(Min of 3 ways )
3. how will you proove that arrays are faster than lists,and whhy it is faster tell it in a point.
4. Array Creation: 
    - a.Create a 4D NumPy array containing the first 12 positive integers as arr1,ofter creating check the dimension of the              array and also dtype of the elements.
    - b.Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1 and make every element as                  string.and ofter creating check what is the shape of the array.
5. create an array with all zeros without using np.zeros method.
6. create an array and perform all the arthamatic operations on it 
7. Create a 2x2 matrix A with elements from 1 to 4 and another matrix B with elements from 5 to 8.
   - a. Add matrices A and B.
   - b. Multiply matrices A and B element-wise.
   - c. Find the dot product of matrices A and B.
8. Create a 3x3 matrix C with random integers.
   - a. Find the sum of each row in matrix C.
   - b. Find the sum of each column in matrix C.
   - c. Find the product of all elements in matrix C.  
9. a. Create a boolean array based on whether elements in matrix C are greater than 0.
   b. Use logical AND operation to find elements greater than 2 and less than 5 in matrix C.
10. a. Access the element in the second row and third column of matrix C.
    b. Slice the first two columns of matrix C.
    c. Extract all elements greater than 3 from matrix C.


Note:- 
  1) All create a new repository In github for data analysis and upload the assignment file there 
  2) Use comments for question and below write down the answers

In [1]:
#1.What are the differences between list and array?
#Ans.
#Lists-
#(i)Lists can store different types of data(heterogeneous)
#(ii)Lists occupy large memory as they are dynamically allocated.
#(iii)Operations are applied on the complete list as one whole element.For eg-[1,2,3]*2=[1,2,3,1,2,3]
#(iv)There is no need to explicitly import a module for declaration.
#(v)Computation is slow,mainly because of above features.
#(vi)Lists are one-dimensional.
#(vii)Preferrable for short sequence of data items

#Arrays-
#(i)Arrays store same type of data(homogeneous).If in case of different types of data given, all data elements are converted to
#same data type,with the order of preference-1.str,2.complex,3.float,4.integer
#(ii)Arrays consume less memory as we can mention the dtatatype to be used(Like int8,int16 etc.)
#(iii)Operations are applied on each element of the array.For eg-if x=np.array([1,2,3]), np.add(x,2)=np.array([3,4,5])
#(iv)There is need to explicitly import a module for declaration.
#(v)Computation is fast, approximately a 100 times faster than lists
#(vi)Arrays are n-dimensional.
#(vii)Preferrable for long sequence of data items.

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [37]:
#2.Write python code to create 3d array in different ways with 15 elements.(Min of 3 ways )

#(i)

array_1=np.array([[[1,2],[2,3],[3,4]]])
print("3D array created by creating lists inside list 3 times: ")
print(array_1)

#(ii)

array_2=np.array([1,2,3],ndmin=3)
print("3D array created by specifying the dimension using ndmin parameter: ")
print(array_2)

#(iii)

import random
x=np.random.random((1,8))
print("3D array created by reshaping a 2D array: ")
array_3=x.reshape(2,2,2)
print(array_3)

3D array created by creating lists inside list 3 times: 
[[[1 2]
  [2 3]
  [3 4]]]
3D array created by specifying the dimension using ndmin parameter: 
[[[1 2 3]]]
3D array created by reshaping a 2D array: 
[[[0.75958034 0.2945683 ]
  [0.47593591 0.0386422 ]]

 [[0.78333215 0.29548953]
  [0.59442257 0.36066673]]]


In [49]:
#3.How will you proove that arrays are faster than lists,and why it is faster tell it in a point?

import time
sta=time.time()
ar=np.arange(1,1000000)
eta=time.time()
print(sta-eta)

stl=time.time()
l=[]
for y in range(1,1000000):
    l.append(y)
etl=time.time()
print(stl-etl)

#In the above code, we use the time() of the time module to determine the amount of time taken to create an array and a list.
#Clearly,we can see that an array is created much faster as compared to a list, almost a 100 times faster
#One of the main reasons for this is that arrays consume less memory because the datatype can be specified(default is float)
#Whereas lists consume large amounts of memory as they are dynamically allocated

-0.002000093460083008
-0.1149740219116211


In [92]:
#4.Array Creation:
#a.Create a 4D NumPy array containing the first 12 positive integers as array,
#after creating check the dimension of the array and also dtype of the elements.
#b.Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1 and make every element as string,
#and ofter creating check what is the shape of the array.

#(a)
arr4=np.array(range(1,13),ndmin=4)
print("(a) \n4D Array containg first 12 positive integers as array: ",arr4)
print("Dimension of the array: ",arr4.ndim)
print("Datatype of the elements: ",arr4.dtype)

#(b)
arR=np.random.random(20)
arr3d=np.array(arR,ndmin=3,dtype=str)
print("(b) \n3D Array containing 20 random elements between 0 and 1, converted string datatype: ")
print(arr3d)
print("Shape of the array: ",arr3d.shape)

(a) 
4D Array containg first 12 positive integers as array:  [[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]]
Dimension of the array:  4
Datatype of the elements:  int32
(b) 
3D Array containing 20 random elements between 0 and 1, converted string datatype: 
[[['0.06470618202846423' '0.8320396089858121' '0.014507586061734634'
   '0.9306327323731451' '0.14746038644279724' '0.4165185376739984'
   '0.836446468218077' '0.6679558393786975' '0.5532641055176782'
   '0.5906781407194778' '0.21031442482456453' '0.7503009774040162'
   '0.18814270747745332' '0.08645652840771068' '0.9885111272220921'
   '0.8725412844831331' '0.6753985792011903' '0.8219075830922911'
   '0.6082133970637666' '0.10055351847233296']]]
Shape of the array:  (1, 1, 20)


In [104]:
#5.Create an array with all zeros without using np.zeros method.

zarray=np.full((3,3,),0,dtype=int) #here, we used the full() instead of the np.zeroes() method
print(zarray)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [142]:
#6. Create an array and perform all the arithemetic operations on it

a1=np.array([1,2,3])
print("array+2= ",np.add(a1,2))
print("array-2= ",np.subtract(a1,2))
print("array*2= ",np.multiply(a1,2))
print("array/2= ",np.divide(a1,2))
print("array//2= ",np.floor_divide(a1,2))
print("array%2= ",np.mod(a1,2))

#arithemtic operations can also be performed between two arrays(of same dimension and shape)
a2=np.array([4,5,6])
print("array1+array2= ",np.add(a1,a2))
print("array1-array2= ",np.subtract(a1,a2))
print("array1*array2= ",np.multiply(a1,a2))
print("arraya/array2= ",np.divide(a1,a2))
print("array1//array2= ",np.floor_divide(a1,a2))
print("array1%array2= ",np.mod(a1,a2))

array+2=  [3 4 5]
array-2=  [-1  0  1]
array*2=  [2 4 6]
array/2=  [0.5 1.  1.5]
array//2=  [0 1 1]
array%2=  [1 0 1]
array1+array2=  [5 7 9]
array1-array2=  [-3 -3 -3]
array1*array2=  [ 4 10 18]
arraya/array2=  [0.25 0.4  0.5 ]
array1//array2=  [0 0 0]
array1%array2=  [1 2 3]


In [158]:
#7.Create a 2x2 matrix A with elements from 1 to 4 and another matrix B with elements from 5 to 8.
#a. Add matrices A and B.
#b. Multiply matrices A and B element-wise.
#c. Find the dot product of matrices A and B.

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("a)\nAdding matrices A and B:\n",np.add(A,B))
print("b)\nMultiplying matrices A and B element-wise:\n",np.multiply(A,B))
print("c)\nDot product of matrices A and B:\n",np.dot(A,B))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
a)
Adding matrices A and B:
 [[ 6  8]
 [10 12]]
b)
Multiplying matrices A and B element-wise:
 [[ 5 12]
 [21 32]]
c)
Dot product of matrices A and B:
 [[19 22]
 [43 50]]


In [205]:
#8.Create a 3x3 matrix C with random integers.
#a. Find the sum of each row in matrix C.
#b. Find the sum of each column in matrix C.
#c. Find the product of all elements in matrix C.

C=np.random.randint(100,size=9).reshape(3,3)
print("3X3 matrix C with random integers:\n",C)
print("(a)\nSum of each row in matrix C:\n",np.sum(C,axis=1))
print("(b)\nSum of each column in matrix C:\n",np.sum(C,axis=0))
print("(c)\nProduct of all elements in matrix C:\n",np.prod(C))

3X3 matrix C with random integers:
 [[94 95 70]
 [63 82 10]
 [44 19 60]]
(a)
Sum of each row in matrix C:
 [259 155 123]
(b)
Sum of each column in matrix C:
 [201 196 140]
(c)
Product of all elements in matrix C:
 455513856


In [214]:
#9.a. Create a boolean array based on whether elements in matrix C are greater than 0.
#  b. Use logical AND operation to find elements greater than 2 and less than 5 in matrix C.

C=np.random.randint(6,size=12).reshape(4,3)
print("Matrix C:\n",C)
print("a)\nBoolean array showing whether elements in C are greater than zero:\n",C>0)
print("b)\nElements greater than 2 and less than 5 in C: ",C[(C>2)&(C<5)])


Matrix C:
 [[3 0 3]
 [3 2 2]
 [1 5 5]
 [0 0 0]]
a)
Boolean array showing whether elements in C are greater than zero:
 [[ True False  True]
 [ True  True  True]
 [ True  True  True]
 [False False False]]
b)
Elements greater than 2 and less than 5 in C:  [3 3 3]


In [220]:
#10. a. Access the element in the second row and third column of matrix C.
#    b. Slice the first two columns of matrix C.
#    c. Extract all elements greater than 3 from matrix C.

C=np.random.randint(10,size=15).reshape(3,5)
print(C)
print("a)\nElement in 2nd row and 3rd column of C: ",C[[1],[2]])
print("b)\nFirst two columns of matrix C:\n",C[0:,0:2])
print("c)\nAll elements greater than 3 from matrix C: ",C[C>3])

[[5 3 0 7 3]
 [5 1 8 4 6]
 [1 8 9 7 3]]
a)
Element in 2nd row and 3rd column of C:  [8]
b)
First two columns of matrix C:
 [[5 3]
 [5 1]
 [1 8]]
c)
All elements greater than 3 from matrix C:  [5 7 5 8 4 6 8 9 7]
